# Generated by Django 2.2 on 2021-03-26 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='timeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lector', models.CharField(max_length=125)),
                ('topic', models.CharField(max_length=125)),
                ('description', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=250)),
                ('tag', models.CharField(max_length=250)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waktu', to='discourse.timeSchedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesantren', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
