# Generated by Django 2.2 on 2021-03-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeschedule',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
