# Generated by Django 2.2 on 2021-03-26 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discourse', '0002_auto_20210326_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
